name: aander
favicon: null
layout_spectrum: 0.9186498164199293
typography_spectrum: 0.5681343718897551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7046468497719616
  lightness: 0.9650933118537068
  saturation: 0.24749710294418037
  rhythmicContrast: 0.5131569283548743
purpose: []
